variables:
  DOCKER_DRIVER: overlay2

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

maven-build-job:       # This job runs in the build stage, which runs first.
  image: maven:latest
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn package
  artifacts:
    paths:
      - target/*.jar


deploy-job:      # This job runs in the deploy stage.
  image: docker:latest
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  services:
    - name: docker:dind
  script:
    - echo "Deploying application..."
    - docker build -t registry.gitlab.com/quantus-eng/cs-psp-service-provider . -f dockerfile
    - echo "Login to gitlab..."
    - echo $CI_JOB_TOKEN | docker login --username=gitlab-ci-token --password-stdin registry.gitlab.com
    - echo "Pushing to gitlab..."
    - docker push registry.gitlab.com/quantus-eng/cs-psp-service-provider
    - echo "Application successfully deployed."